### PR TITLE
Add basic travis config

### PR DESCRIPTION
**Pull request by Nemo157**
## How Has This Been Tested?
In CI hopefully

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Nemo157** [comment]
@yoshuawuyts could you enable Travis for this repo?

**Comment by Nemo157** [comment]
@tirr-c it looks like you probably have access to Travis for this org as well, are you able to enable it since Yoshua seems busy?

**Comment by tirr-c** [comment]
@Nemo157 Sure, should be working now!

**Comment by Nemo157** [comment]
@tirr-c looks like it, thanks!

**Pull request merged**
